name: uk_digital_id_wallet
description: UK Digital Identity Platform - Secure Mobile Wallet Application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+10

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI Components & Navigation
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  animations: ^2.0.11
  flutter_staggered_animations: ^1.1.1
  lottie: ^2.7.0
  
  # State Management
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  
  # Networking & API
  http: ^1.1.0
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Storage & Security
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication & Biometrics
  local_auth: ^2.1.7
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6
  
  # Camera & QR Code
  camera: ^0.10.5+5
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  image_picker: ^1.0.4
  
  # Permissions & Device Info
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  
  # Connectivity & Location
  connectivity_plus: ^5.0.1
  geolocator: ^10.1.0
  
  # Encryption & Security
  crypto: ^3.0.3
  encrypt: ^5.0.1
  pointycastle: ^3.7.3
  
  # Utilities
  intl: ^0.18.1
  logger: ^2.0.2+1
  uuid: ^4.1.0
  path_provider: ^2.1.1
  url_launcher: ^6.2.1
  
  # Wallet & Payments
  flutter_credit_card: ^4.0.1
  
  # Firebase Services
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  
  # Biometric & Document Verification
  flutter_face_api: ^2.0.0
  
  # Charts & Visualization
  fl_chart: ^0.64.0
  
  # Testing & Development
  mockito: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting & Code Quality
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  hive_generator: ^2.0.1
  
  # Testing
  integration_test:
    sdk: flutter
  patrol: ^2.6.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/documents/
    
  # Fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 23 # Android 6.0+
  
flutter_native_splash:
  color: "#1565C0"
  image: assets/images/splash_logo.png
  android_12:
    image: assets/images/splash_logo_android12.png